name: Publish Packages
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag_name:
        description: Version to be published e.g. 1.0.0
        type: string
jobs:
  Build-And-Publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm --no-git-tag-version version ${{ github.event.release.tag_name || inputs.tag_name }} --workspaces
      - run: npm run build --workspace=@hubfx/core
      - run: npm publish --workspace=@hubfx/core --access public
      - run: npm install @hubfx/core@${{ github.event.release.tag_name || inputs.tag_name }} --workspace=@hubfx/forms
      - run: npm run build --workspace=@hubfx/forms
      - run: npm publish --workspace=@hubfx/forms --access public
      - run: npm install @hubfx/forms@${{ github.event.release.tag_name || inputs.tag_name }} --workspace=@hubfx/react-forms
      - run: npm run build --workspace=@hubfx/react-forms
      - run: npm publish --workspace=@hubfx/react-forms --access public
